[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["googleapis"]

# 1) First: send /api/* to functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# 2) Last: SPA fallback (do NOT force)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200