[build]
   command = "npm run build"
   publish = "dist"
   functions = "netlify/functions"

 [functions]
-  external_node_modules = ["@netlify/blobs"]
+  # You can drop "@netlify/blobs" if you no longer use it.
+  external_node_modules = ["googleapis"]

+[# Optional but recommended to avoid old Node runtimes]
+[build.environment]
+  NODE_VERSION = "20"