[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["googleapis"]

# ---- API redirects (explicit) ----
[[redirects]]
  from = "/api/managers"
  to   = "/.netlify/functions/managers"
  status = 200
  force = true

[[redirects]]
  from = "/api/managers/"
  to   = "/.netlify/functions/managers"
  status = 200
  force = true

[[redirects]]
  from = "/api/profile-request"
  to   = "/.netlify/functions/profile-request"
  status = 200
  force = true

[[redirects]]
  from = "/api/profile-request/"
  to = "/.netlify/functions/profile-request"
  status = 200
  force = true


[[redirects]]
  from = "/api/manager"
  to   = "/.netlify/functions/manager"
  status = 200
  force = true

[[redirects]]
  from = "/api/manager/*"
  to   = "/.netlify/functions/manager"
  status = 200
  force = true

# keep your /admin redirect, then the SPA fallback LAST

# ---- Admin (static) ----
[[redirects]]
  from = "/admin"
  to   = "/admin/index.html"
  status = 200

# ---- SPA fallback (must be last!) ----
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200