[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["googleapis"]  # ok to keep even if unused

# Map /api/* to functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# SPA fallback — must be last and not forced
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200