[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["googleapis"]

# API → Netlify Functions
[[redirects]]
  from = "/api/managers"
  to = "/.netlify/functions/managers"
  status = 200
  force = true

[[redirects]]
  from = "/api/managers/"
  to = "/.netlify/functions/managers"
  status = 200
  force = true

[[redirects]]
  from = "/api/manager"
  to = "/.netlify/functions/manager"
  status = 200
  force = true

[[redirects]]
  from = "/api/manager/*"
  to = "/.netlify/functions/manager"
  status = 200
  force = true

[[redirects]]
  from = "/api/profile-request"
  to = "/.netlify/functions/profile-request"
  status = 200
  force = true

[[redirects]]
  from = "/api/profile-request/"
  to = "/.netlify/functions/profile-request"
  status = 200
  force = true

# Static pages (optional, if you have these)
[[redirects]]
  from = "/admin"
  to   = "/admin/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/request"
  to   = "/public/request/index.html"
  status = 200
  force = true

# SPA fallback LAST
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200