[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  # If you still use Netlify Blobs, keep it here too: ["googleapis", "@netlify/blobs"]
  external_node_modules = ["googleapis"]

# Optional but recommended to avoid old Node runtimes
[build.environment]
  NODE_VERSION = "20"

# API routes (explicit; handle trailing slashes and slugs)
[[redirects]]
  from = "/api/managers"
  to   = "/.netlify/functions/managers"
  status = 200

[[redirects]]
  from = "/api/managers/"
  to   = "/.netlify/functions/managers"
  status = 200

[[redirects]]
  from = "/api/profile-request"
  to   = "/.netlify/functions/profile-request"
  status = 200

[[redirects]]
  from = "/api/manager/*"
  to   = "/.netlify/functions/manager"
  status = 200

# Static /admin (must come before SPA fallback)
[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

# SPA fallback (must be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200