[build]
  command = "npm run build"
  publish = "dist"  # Changed from "build" to "dist"
  functions = "netlify/functions"

# API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Static pages (must come before SPA fallback)
[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

# SPA fallback (must be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200