[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["googleapis"]

# API route shortcuts
[[redirects]]
  from = "/api/managers"
  to = "/.netlify/functions/managers"
  status = 200
  force = true

[[redirects]]
  from = "/api/manager"
  to = "/.netlify/functions/manager"
  status = 200
  force = true

[[redirects]]
  from = "/api/profile-request"
  to = "/.netlify/functions/profile-request"
  status = 200
  force = true

# SPA fallback (keeps hash routing happy)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200